fix: fixing MGC_PATH on pipe

diff --git a/.github/workflows/test-on-pr.yml b/.github/workflows/test-on-pr.yml
--- a/.github/workflows/test-on-pr.yml
+++ b/.github/workflows/test-on-pr.yml
@@ -14,6 +14,7 @@ jobs:
     
     env:
       MGC_API_KEY: ${{ secrets.MGC_API_KEY }}
+      MGC_PATH: ${{ vars.MGC_PATH }}
 
     steps:
       - name: Checkout code
@@ -39,10 +40,14 @@ jobs:
           sudo apt update
           sudo apt install -y mgccli
 
-      - name: Verify MGC_API_KEY and CLI
+      - name: Verify MGC_API_KEY and MGC_PATH and CLI
         run: |
           if [ -z "$MGC_API_KEY" ]; then
             echo "Error: MGC_API_KEY is not set in GitHub Secrets."
+            exit 1
+          fi
+          if [ -z "$MGC_PATH" ]; then
+            echo "Error: MGC_PATH is not set in GitHub Variables."
             exit 1
           fi
           mgc --version
